<?xml version="1.0" encoding="utf-8"?><Database Name="TestP4" Class="TestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=TestP4;Integrated Security=True" SettingsObjectName="TestDesigner.Properties.Settings" SettingsPropertyName="TestP4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCompany" Member="tblCompanies">
    <Type Name="tblCompany">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyFullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyFullNameEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ComAcronymName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DirectorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxRegNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TaxRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tblDivision" Member="tblDivisions">
    <Type Name="tblDivision">
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BranchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblDivision_tblDepartment" Member="tblDepartments" ThisKey="DivisionID" OtherKey="DivisionID" Type="tblDepartment" />
    </Type>
  </Table>
  <Table Name="dbo.tblDepartment" Member="tblDepartments">
    <Type Name="tblDepartment">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="tblDepartment_tblSection" Member="tblSections" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="tblSection" />
      <Association Name="tblDivision_tblDepartment" Member="tblDivision" ThisKey="DivisionID" OtherKey="DivisionID" Type="tblDivision" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSection" Member="tblSections">
    <Type Name="tblSection">
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblSection_tblGroup" Member="tblGroups" ThisKey="SectionID" OtherKey="SectionID" Type="tblGroup" />
      <Association Name="tblDepartment_tblSection" Member="tblDepartment" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="tblDepartment" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroup" Member="tblGroups">
    <Type Name="tblGroup">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblSection_tblGroup" Member="tblSection" ThisKey="SectionID" OtherKey="SectionID" Type="tblSection" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>