<?xml version="1.0" encoding="utf-8"?><Database Name="phanmemtinhluon_P4" Class="DataDaigramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=112.78.2.166,1455;Initial Catalog=phanmemtinhluon_P4;Persist Security Info=True;User ID=phanmemtinhluon_saP4" SettingsObjectName="HPA.SQL.Properties.Settings" SettingsPropertyName="phanmemtinhluon_P4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblSC_Login" Member="tblSC_Logins">
    <Type Name="tblSC_Login">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminRight" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LastChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSC_Object" Member="tblSC_Objects">
    <Type Name="tblSC_Object">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSC_Right" Member="tblSC_Rights">
    <Type Name="tblSC_Right">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullAccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEN_Menu" Member="MEN_Menus">
    <Type Name="MEN_Menu">
      <Column Name="MenuID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsModal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LinkMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsCollapsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShortcutKeys" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SupperAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblMD_Message" Member="tblMD_Messages">
    <Type Name="tblMD_Message">
      <Column Name="MessageID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblDepartment" Member="tblDepartments">
    <Type Name="tblDepartment">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDivision" Member="tblDivisions">
    <Type Name="tblDivision">
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BranchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCompany" Member="tblCompanies">
    <Type Name="tblCompany">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyFullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyFullNameEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ComAcronymName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DirectorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxRegNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TaxRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroup" Member="tblGroups">
    <Type Name="tblGroup">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSection" Member="tblSections">
    <Type Name="tblSection">
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SC_Login_CheckLogin" Method="SC_Login_CheckLogin">
    <Parameter Name="LoginName" Parameter="loginName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Message" Method="Get_Message">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.String" DbType="Char(50)" />
    <Parameter Name="Language" Parameter="language" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SC_USEROBJECTRIGHT_GET" Method="SC_USEROBJECTRIGHT_GET">
    <Parameter Name="p_FullClassName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="p_LoginID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Menu_Load" Method="sp_Menu_Load" IsComposable="true">
    <Parameter Name="LanguageID" Parameter="languageID" Type="System.String" DbType="Char(2)" />
    <Parameter Name="LoginID" Parameter="loginID" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
</Database>