<?xml version="1.0" encoding="utf-8"?><Database Name="phanmemtinhluon_P4" Class="DataDaigramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=112.78.2.166,1455;Initial Catalog=phanmemtinhluon_P4;Persist Security Info=True;User ID=phanmemtinhluon_saP4" SettingsObjectName="HPA.SQL.Properties.Settings" SettingsPropertyName="phanmemtinhluon_P4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblSC_Login" Member="tblSC_Logins">
    <Type Name="tblSC_Login">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminRight" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LastChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSC_Object" Member="tblSC_Objects">
    <Type Name="tblSC_Object">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSC_Right" Member="tblSC_Rights">
    <Type Name="tblSC_Right">
      <Column Name="ObjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullAccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEN_Menu" Member="MEN_Menus">
    <Type Name="MEN_Menu">
      <Column Name="MenuID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsModal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LinkMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsCollapsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShortcutKeys" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SupperAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblMD_Message" Member="tblMD_Messages">
    <Type Name="tblMD_Message">
      <Column Name="MessageID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblCompany" Member="tblCompanies">
    <Type Name="tblCompany">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyFullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyFullNameEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ComAcronymName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DirectorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TaxRegNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TaxRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tblEmployee" Member="tblEmployees">
    <Type Name="tblEmployee">
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WorkingPlaceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PositionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BusinessPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="HomeFax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ID_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ID_Issue_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_Issue_Place" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_ProvinceID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Marital" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FalseDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BirthPlace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NativeCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeStatusID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TerminateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkingStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BasicInfoNotes" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Religion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassportNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PassportIssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PassportExpiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PassportPlace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Transport" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CallName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OfficeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HomeEmail" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HomeNotes" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Official" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LBNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractStartDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractEndDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LabourName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsWorker" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccPoint" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="IsDeclaredSI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SignedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TerminateReasonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProbationEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccOwner" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhotoImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WorkPermitNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="WorkPermit_IssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkPermit_ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TemporaryPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="IsOTInSalary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TaxRegNo" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Ethnic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DistrictID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="ProvinceID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tmpDistrictID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="tmpProvinceID" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="tmpWard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EducationalBase" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResidentAdd" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsNonTaxable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LineManagerID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AreaSupID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IDForBankTransfer" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EmployeeTypeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacilityCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FacilityTown" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="WorkingTimePercent" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="WHPerWeek" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="NewCostCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OldCostCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductionLine" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaxRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TaxRegPlace" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLabourContract" Member="tblLabourContracts">
    <Type Name="tblLabourContract">
      <Column Name="ContractID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContractNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LBNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LabourName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractStartDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractEndDay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LBIssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LBIssuePlace" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsFirstSign" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChuyenMonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalaryCode" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WorkingTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsProbation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LabourAssignTaskID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isSigned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isLowSalary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitmentKind" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PrintAppendixDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSC_DepartmentView" Member="tblSC_DepartmentViews">
    <Type Name="tblSC_DepartmentView">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ViewInfo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblWSchedule" Member="tblWSchedules">
    <Type Name="tblWSchedule">
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScheduleDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShiftID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HolidayStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LeaveStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Approved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDivision" Member="tblDivisions">
    <Type Name="tblDivision">
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BranchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblDivision_tblDepartment" Member="tblDepartments" ThisKey="DivisionID" OtherKey="DivisionID" Type="tblDepartment" />
    </Type>
  </Table>
  <Table Name="dbo.tblDepartment" Member="tblDepartments">
    <Type Name="tblDepartment">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="tblDepartment_tblSection" Member="tblSections" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="tblSection" />
      <Association Name="tblDivision_tblDepartment" Member="tblDivision" ThisKey="DivisionID" OtherKey="DivisionID" Type="tblDivision" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSection" Member="tblSections">
    <Type Name="tblSection">
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblSection_tblGroup" Member="tblGroups" ThisKey="SectionID" OtherKey="SectionID" Type="tblGroup" />
      <Association Name="tblDepartment_tblSection" Member="tblDepartment" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="tblDepartment" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroup" Member="tblGroups">
    <Type Name="tblGroup">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="JapaneseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VietnameseName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Foreigner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblSection_tblGroup" Member="tblSection" ThisKey="SectionID" OtherKey="SectionID" Type="tblSection" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.SC_Login_CheckLogin" Method="SC_Login_CheckLogin">
    <Parameter Name="LoginName" Parameter="loginName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Message" Method="Get_Message">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.String" DbType="Char(50)" />
    <Parameter Name="Language" Parameter="language" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SC_USEROBJECTRIGHT_GET" Method="SC_USEROBJECTRIGHT_GET">
    <Parameter Name="p_FullClassName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="p_LoginID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Menu_Load" Method="sp_Menu_Load" IsComposable="true">
    <Parameter Name="LanguageID" Parameter="languageID" Type="System.String" DbType="Char(2)" />
    <Parameter Name="LoginID" Parameter="loginID" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.SC_LoginInfor" Method="SC_LoginInfor">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="loginID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SC_LoginInforResult">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AdminRight" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_hr_get_fullname" Method="sp_hr_get_fullname">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LoginID" Parameter="loginID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_hr_get_fullnameResult">
      <Column Name="FullName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SC_DeptSectView_List" Method="SC_DeptSectView_List" IsComposable="true">
    <Parameter Name="LoginID" Parameter="loginID" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
</Database>