using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HPA.Common
{
    public class CommonConst
    {
        public const string NO_RIGHT_TO_ACCESS = "NO_RIGHT_TO_ACCESS";
        public const string PARADISE_INI = "Paradise.ini";
        public const string LOGIN_FAILURE = "LOGIN_FAILURE";
        public const string encryptkey = "acoi9a";
        public const string SEMICOLON_CHAR = ";";
        public const string CPN_STD_NAME = "Vietinsoft";

        public const string LEAVE_CODE = "LeaveCode";
        public const string LEAVE_STATUS = "LeaveStatus";
        public const string ATT_END = "AttEnd";
        public const string WORK_END = "WorkEnd";
        public const string ATT_END_DATE = "AttEndDate";
        public const string ATT_START = "AttStart";
        public const string ATT_START_DATE = "AttStartDate";
        public const string ATT_DATE = "AttDate";
        public const string WORK_START = "WorkStart";
        public const string DESCRIPTION = "Description";
        public const string SHIFT_ID = "ShiftID";
        public const string SHIFT_CODE = "ShiftCode";

        public const string DELETE_CONFIRM = "DELETE_CONFIRM";
        public const string DISCARD_CONFIRM = "DISCARD_CONFIRM";
        public const string PROCESS_DATA_CONFIRM = "PROCESS_DATA_CONFIRM";
        public const string SELECT_SHIFT = "SELECT_SHIFT";
        public const string SELECT_DATE = "SELECT_DATE";
        public const string WRONG_PASSWORD = "WRONG_PASSWORD";
        public const string WRONG_SEX = "WRONG_SEX";
        public const string DATASAVED_SUCCESSFULLY = "SAVEDSUCCESSFULLY";
        public const string UPDATE_SUCCESSFULLY = "UPDATE_SUCCESSFULLY";
        public const string RESTART_SUCCESSFULLY = "RESTART_SUCCESSFULLY";
        public const string POWEROFF_SUCCESSFULLY = "POWEROFF_SUCCESSFULLY";
        public const string UPDATE_FILE_INVALID = "UPDATE_FILE_INVALID";
        public const string LOAD_DATA_FIRST = "LOAD_DATA_FIRST";
        public const string ERROR_LOG_FILE = "Error_log.txt";
        public const string IMPORTDATA_ERROR = "IMPORTDATA_ERROR";
        public const string IMPORTDATA_SUCCESS = "IMPORTDATA_SUCCESS";
        public const string DATA_PROCESSED_SUCCESSFULLY = "DATA_PROCESSED_SUCCESSFULLY";
        public const string DELETE_SUCCESSFULLY = "DELETE_SUCCESSFULLY";
        public const string ID_NUMBER_DUPLICATE = "ID_NUMBER_DUPLICATE";
        public const string SHIFT_CODE_NULL_ERROR = "SHIFT_CODE_NULL_ERROR";
        public const string SHIFT_NAME_NULL_ERROR = "SHIFT_NAME_NULL_ERROR";
        public const string OPEN_FILE_QUES = "OPEN_FILE_QUES";
        public const string SAL_UNLOCK_SUCCESSFULLY = "SAL_UNLOCK_SUCCESSFULLY";
        public const string SAL_CAL_SUCCESSFULLY = "SAL_CAL_SUCCESSFULLY";
        public const string SAL_LOCK_SUCCESSFULLY = "SAL_LOCK_SUCCESSFULLY";
        public const string SAL_CAL_FINISHED_ERROR = "SAL_CAL_FINISHED_ERROR";
        public const string SAL_HAVE_BEEN_LOCK = "SAL_HAVE_BEEN_LOCK";
        public const string SAVE_DATA_QUES = "SAVE_DATA_QUES";
        public const string WSCHEDULE_LOCKED = "WSCHEDULE_LOCKED";
        public const string DATA_LOCKED = "DATA_LOCKED";
        public const string EmployeeCardNotSaved = "EmployeeCardNotSaved";
        public const string EmployeeNotExists = "EmployeeNotExists";
        public const string EmployeeID = "EmployeeID";
        public const string SalaryHistoryID = "SalaryHistoryID";
        public const string FullName = "FullName";
        public const string A_EmployeeTypeID = "@EmployeeTypeID";
        public const string EmployeeTypeID = "EmployeeTypeID";
        public const string A_EmployeeID = "@EmployeeID";
        public const string A_LoginID = "@LoginID";
        public const string A_FromDate = "@FromDate";
        public const string A_ToDate = "@ToDate";
        public const string A_Month = "@Month";
        public const string A_Year = "@Year";
        public const string Password = "Password";
        public const int NAG_ONCE = -1;
        public const string NAG_ONCE_STR = "-1";
        public const string ALL = "(All)";
        public const string SectionID = "SectionID";
        public const string SectionName = "SectionName";
        public const string GroupID = "GroupID";
        public const string GroupName = "GroupName";
        public const string DepartmentID = "DepartmentID";
        public const string DepartmentName = "DepartmentName";
        public const string MONKEY_ERROR = "MONKEY_ERROR";
        public const string WARNING_COMPLETE_DATA = "WARNING_COMPLETE_DATA";
        public const string DATADOWNLOAD_SUCCESSFULLY = "DATADOWNLOADSUCCESSFULLY";

        public const string DIS_CONNECT = "DisConnect";
        public const string STATUS = "Status";
        public const string ImageIcon = "ImageIcon";
        public const string MACHINE_NUMBER = "MachineNumber";
        public const string IS_CONNECTED = "IsConnected";
        public const string CONNECTED = "Connected";
        public const string NOT_CONNECTED_YET = "NOT_CONNECTED_YET";
        public const string CONNECT_TO_DIVICE_FIRST = "CONNECT_TO_DIVICE_FIRST";
        public const string CONNECTING = "Connecting";
        public const string CONNECT_FAILURE = "ConnectFailure";
        public const string SELECT_MACHINE_FIRST = "SELECT_MACHINE_FIRST";
        public const string CDKEY = "CDKey";
        public const string IP = "IP";
        public const string PORT = "Port";
        public const string LOG_ATT_COUNT = "LogCount";
        public const string MANAGER_COUNT = "managercount";
        public const string USER_COUNT = "usercount";
        public const string FINGER_COUNT = "fingercount";
        public const string PASSWORD_COUNT = "SecretCount";
        public const string SERIAL_NUMBER = "sn";
        public const string MACHINE_ALIAS = "MachineAlias";
        public const string NAME_ON_MACHINE = "NameOnMachine";
        public const string NAME = "Name";
        public const string LOG_TIME = "LogTime";
        public const string VERIFY_MODE = "VerifyMode";
        public const string USER_ID = "UserID";
        public const string PHOTO = "PhotoImage";
        public const string BADGE_NUMBER = "Badgenumber";
        public const string privilege = "privilege";
        public const string FINGERID = "FINGERID";
        public const string Flag = "Flag";
        public const string CARD_NO = "CardNo";
        public const string WORKING_ON_MACHINE = "WORKING_ON_MACHINE";
        public const string READING_DATA = "READING_DATA";
        public const string DOWNLOADING_DATA = "DOWNLOADING_DATA";
        public const string UPLOADING_DATA = "UPLOADING_DATA";
        public const string Template_Text = "Template_Text";

        public const string FROMDATE_TODATE_ERR = "FROMDATE_TODATE_ERR";
        public const string DATETIME_NULL = "DATETIME_NULL";
        public const string EMAIL_SEND_SUCCESSFULLY = "EMAIL_SEND_SUCCESSFULLY";
        public const string EMAIL_ADDRESS_NULL = "EMAIL_ADDRESS_NULL";
        public const string EMAIL = "Email";
        public const string EMAIL_BODY_NULL = "EMAIL_BODY_NULL";
        public const string SALARY_CODE_REQUIRED = "SALARY_CODE_REQUIRED";
        public const string INPUT_DATA_REQUIRED = "INPUT_DATA_REQUIRED";
        public const string INPUT_EMPLOYEEID = "INPUT_EMPLOYEEID";
        public const string SAVE_DATA_FIRST = "SAVE_DATA_FIRST";
        public const string TAB_KEY = "TAB";
        public const string F4_KEY = "F4";
        public const string PASS_WRONG = "PASS_WRONG";
        public const string EDIT_VALUE = "EditValue";
    }
}
