<?xml version="1.0" encoding="utf-8"?><Database Name="phanmemtinhluon_P4" Class="DataDaigramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=112.78.2.166,1455;Initial Catalog=phanmemtinhluon_P4;Persist Security Info=True;User ID=phanmemtinhluon_saP4" SettingsObjectName="HPA.SQL.Properties.Settings" SettingsPropertyName="phanmemtinhluon_P4ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SC_Login_CheckLogin" Method="SC_Login_CheckLogin">
    <Parameter Name="LoginName" Parameter="loginName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Message" Method="Get_Message">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.String" DbType="Char(50)" />
    <Parameter Name="Language" Parameter="language" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SC_USEROBJECTRIGHT_GET" Method="SC_USEROBJECTRIGHT_GET">
    <Parameter Name="p_FullClassName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="p_LoginID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>