#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPA.SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="phanmemtinhluon_P4")]
	public partial class DataDaigramDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblSC_Login(tblSC_Login instance);
    partial void UpdatetblSC_Login(tblSC_Login instance);
    partial void DeletetblSC_Login(tblSC_Login instance);
    partial void InserttblSC_Object(tblSC_Object instance);
    partial void UpdatetblSC_Object(tblSC_Object instance);
    partial void DeletetblSC_Object(tblSC_Object instance);
    partial void InserttblSC_Right(tblSC_Right instance);
    partial void UpdatetblSC_Right(tblSC_Right instance);
    partial void DeletetblSC_Right(tblSC_Right instance);
    partial void InsertMEN_Menu(MEN_Menu instance);
    partial void UpdateMEN_Menu(MEN_Menu instance);
    partial void DeleteMEN_Menu(MEN_Menu instance);
    partial void InserttblMD_Message(tblMD_Message instance);
    partial void UpdatetblMD_Message(tblMD_Message instance);
    partial void DeletetblMD_Message(tblMD_Message instance);
    partial void InserttblDepartment(tblDepartment instance);
    partial void UpdatetblDepartment(tblDepartment instance);
    partial void DeletetblDepartment(tblDepartment instance);
    partial void InserttblDivision(tblDivision instance);
    partial void UpdatetblDivision(tblDivision instance);
    partial void DeletetblDivision(tblDivision instance);
    partial void InserttblCompany(tblCompany instance);
    partial void UpdatetblCompany(tblCompany instance);
    partial void DeletetblCompany(tblCompany instance);
    partial void InserttblGroup(tblGroup instance);
    partial void UpdatetblGroup(tblGroup instance);
    partial void DeletetblGroup(tblGroup instance);
    partial void InserttblSection(tblSection instance);
    partial void UpdatetblSection(tblSection instance);
    partial void DeletetblSection(tblSection instance);
    #endregion
		
		public DataDaigramDataContext() : 
				base(global::HPA.SQL.Properties.Settings.Default.phanmemtinhluon_P4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDaigramDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDaigramDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDaigramDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDaigramDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblSC_Login> tblSC_Logins
		{
			get
			{
				return this.GetTable<tblSC_Login>();
			}
		}
		
		public System.Data.Linq.Table<tblSC_Object> tblSC_Objects
		{
			get
			{
				return this.GetTable<tblSC_Object>();
			}
		}
		
		public System.Data.Linq.Table<tblSC_Right> tblSC_Rights
		{
			get
			{
				return this.GetTable<tblSC_Right>();
			}
		}
		
		public System.Data.Linq.Table<MEN_Menu> MEN_Menus
		{
			get
			{
				return this.GetTable<MEN_Menu>();
			}
		}
		
		public System.Data.Linq.Table<tblMD_Message> tblMD_Messages
		{
			get
			{
				return this.GetTable<tblMD_Message>();
			}
		}
		
		public System.Data.Linq.Table<tblDepartment> tblDepartments
		{
			get
			{
				return this.GetTable<tblDepartment>();
			}
		}
		
		public System.Data.Linq.Table<tblDivision> tblDivisions
		{
			get
			{
				return this.GetTable<tblDivision>();
			}
		}
		
		public System.Data.Linq.Table<tblCompany> tblCompanies
		{
			get
			{
				return this.GetTable<tblCompany>();
			}
		}
		
		public System.Data.Linq.Table<tblGroup> tblGroups
		{
			get
			{
				return this.GetTable<tblGroup>();
			}
		}
		
		public System.Data.Linq.Table<tblSection> tblSections
		{
			get
			{
				return this.GetTable<tblSection>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_Login_CheckLogin")]
		public int SC_Login_CheckLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginName", DbType="VarChar(20)")] string loginName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="VarChar(20)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loginName, passWord);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_Message")]
		public int Get_Message([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageID", DbType="Char(50)")] string messageID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="Char(2)")] string language, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="NVarChar(MAX)")] ref string content)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), messageID, language, content);
			content = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_USEROBJECTRIGHT_GET")]
		public int SC_USEROBJECTRIGHT_GET([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_FullClassName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_LoginID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_FullClassName, p_LoginID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Menu_Load", IsComposable=true)]
		public object sp_Menu_Load([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Char(2)")] string languageID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoginID", DbType="Int")] System.Nullable<int> loginID)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), languageID, loginID).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSC_Login")]
	public partial class tblSC_Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoginID;
		
		private string _LoginName;
		
		private string _PassWord;
		
		private string _EmployeeID;
		
		private System.Nullable<int> _DepartmentID;
		
		private System.Nullable<byte> _AdminRight;
		
		private System.Nullable<System.DateTime> _LastChangedDate;
		
		private System.Nullable<int> _DivisionID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginIDChanging(int value);
    partial void OnLoginIDChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnDepartmentIDChanging(System.Nullable<int> value);
    partial void OnDepartmentIDChanged();
    partial void OnAdminRightChanging(System.Nullable<byte> value);
    partial void OnAdminRightChanged();
    partial void OnLastChangedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastChangedDateChanged();
    partial void OnDivisionIDChanging(System.Nullable<int> value);
    partial void OnDivisionIDChanged();
    #endregion
		
		public tblSC_Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this.OnLoginIDChanging(value);
					this.SendPropertyChanging();
					this._LoginID = value;
					this.SendPropertyChanged("LoginID");
					this.OnLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this.OnLoginNameChanging(value);
					this.SendPropertyChanging();
					this._LoginName = value;
					this.SendPropertyChanged("LoginName");
					this.OnLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="VarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(20)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
		public System.Nullable<int> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminRight", DbType="TinyInt")]
		public System.Nullable<byte> AdminRight
		{
			get
			{
				return this._AdminRight;
			}
			set
			{
				if ((this._AdminRight != value))
				{
					this.OnAdminRightChanging(value);
					this.SendPropertyChanging();
					this._AdminRight = value;
					this.SendPropertyChanged("AdminRight");
					this.OnAdminRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastChangedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastChangedDate
		{
			get
			{
				return this._LastChangedDate;
			}
			set
			{
				if ((this._LastChangedDate != value))
				{
					this.OnLastChangedDateChanging(value);
					this.SendPropertyChanging();
					this._LastChangedDate = value;
					this.SendPropertyChanged("LastChangedDate");
					this.OnLastChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionID", DbType="Int")]
		public System.Nullable<int> DivisionID
		{
			get
			{
				return this._DivisionID;
			}
			set
			{
				if ((this._DivisionID != value))
				{
					this.OnDivisionIDChanging(value);
					this.SendPropertyChanging();
					this._DivisionID = value;
					this.SendPropertyChanged("DivisionID");
					this.OnDivisionIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSC_Object")]
	public partial class tblSC_Object : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ObjectID;
		
		private string _ObjectName;
		
		private string _Description;
		
		private System.Nullable<bool> _Visible;
		
		private System.Nullable<int> _ParentObjectID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectIDChanging(int value);
    partial void OnObjectIDChanged();
    partial void OnObjectNameChanging(string value);
    partial void OnObjectNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnVisibleChanging(System.Nullable<bool> value);
    partial void OnVisibleChanged();
    partial void OnParentObjectIDChanging(System.Nullable<int> value);
    partial void OnParentObjectIDChanged();
    #endregion
		
		public tblSC_Object()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this.OnObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectID = value;
					this.SendPropertyChanged("ObjectID");
					this.OnObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectName", DbType="VarChar(100)")]
		public string ObjectName
		{
			get
			{
				return this._ObjectName;
			}
			set
			{
				if ((this._ObjectName != value))
				{
					this.OnObjectNameChanging(value);
					this.SendPropertyChanging();
					this._ObjectName = value;
					this.SendPropertyChanged("ObjectName");
					this.OnObjectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(25)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentObjectID", DbType="Int")]
		public System.Nullable<int> ParentObjectID
		{
			get
			{
				return this._ParentObjectID;
			}
			set
			{
				if ((this._ParentObjectID != value))
				{
					this.OnParentObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ParentObjectID = value;
					this.SendPropertyChanged("ParentObjectID");
					this.OnParentObjectIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSC_Right")]
	public partial class tblSC_Right : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ObjectID;
		
		private int _LoginID;
		
		private System.Nullable<int> _FullAccess;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectIDChanging(int value);
    partial void OnObjectIDChanged();
    partial void OnLoginIDChanging(int value);
    partial void OnLoginIDChanged();
    partial void OnFullAccessChanging(System.Nullable<int> value);
    partial void OnFullAccessChanged();
    #endregion
		
		public tblSC_Right()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this.OnObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectID = value;
					this.SendPropertyChanged("ObjectID");
					this.OnObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this.OnLoginIDChanging(value);
					this.SendPropertyChanging();
					this._LoginID = value;
					this.SendPropertyChanged("LoginID");
					this.OnLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullAccess", DbType="Int")]
		public System.Nullable<int> FullAccess
		{
			get
			{
				return this._FullAccess;
			}
			set
			{
				if ((this._FullAccess != value))
				{
					this.OnFullAccessChanging(value);
					this.SendPropertyChanging();
					this._FullAccess = value;
					this.SendPropertyChanged("FullAccess");
					this.OnFullAccessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MEN_Menu")]
	public partial class MEN_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MenuID;
		
		private string _ClassName;
		
		private System.Nullable<int> _Priority;
		
		private System.Nullable<bool> _IsModal;
		
		private string _ParentMenuID;
		
		private string _LinkMenuID;
		
		private System.Nullable<bool> _IsCollapsed;
		
		private string _AssemblyName;
		
		private string _ShortcutKeys;
		
		private System.Nullable<bool> _IsVisible;
		
		private System.Nullable<bool> _SupperAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIDChanging(string value);
    partial void OnMenuIDChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnIsModalChanging(System.Nullable<bool> value);
    partial void OnIsModalChanged();
    partial void OnParentMenuIDChanging(string value);
    partial void OnParentMenuIDChanged();
    partial void OnLinkMenuIDChanging(string value);
    partial void OnLinkMenuIDChanged();
    partial void OnIsCollapsedChanging(System.Nullable<bool> value);
    partial void OnIsCollapsedChanged();
    partial void OnAssemblyNameChanging(string value);
    partial void OnAssemblyNameChanged();
    partial void OnShortcutKeysChanging(string value);
    partial void OnShortcutKeysChanged();
    partial void OnIsVisibleChanging(System.Nullable<bool> value);
    partial void OnIsVisibleChanged();
    partial void OnSupperAdminChanging(System.Nullable<bool> value);
    partial void OnSupperAdminChanged();
    #endregion
		
		public MEN_Menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MenuID
		{
			get
			{
				return this._MenuID;
			}
			set
			{
				if ((this._MenuID != value))
				{
					this.OnMenuIDChanging(value);
					this.SendPropertyChanging();
					this._MenuID = value;
					this.SendPropertyChanged("MenuID");
					this.OnMenuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(50)")]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsModal", DbType="Bit")]
		public System.Nullable<bool> IsModal
		{
			get
			{
				return this._IsModal;
			}
			set
			{
				if ((this._IsModal != value))
				{
					this.OnIsModalChanging(value);
					this.SendPropertyChanging();
					this._IsModal = value;
					this.SendPropertyChanged("IsModal");
					this.OnIsModalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentMenuID", DbType="VarChar(20)")]
		public string ParentMenuID
		{
			get
			{
				return this._ParentMenuID;
			}
			set
			{
				if ((this._ParentMenuID != value))
				{
					this.OnParentMenuIDChanging(value);
					this.SendPropertyChanging();
					this._ParentMenuID = value;
					this.SendPropertyChanged("ParentMenuID");
					this.OnParentMenuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkMenuID", DbType="VarChar(20)")]
		public string LinkMenuID
		{
			get
			{
				return this._LinkMenuID;
			}
			set
			{
				if ((this._LinkMenuID != value))
				{
					this.OnLinkMenuIDChanging(value);
					this.SendPropertyChanging();
					this._LinkMenuID = value;
					this.SendPropertyChanged("LinkMenuID");
					this.OnLinkMenuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCollapsed", DbType="Bit")]
		public System.Nullable<bool> IsCollapsed
		{
			get
			{
				return this._IsCollapsed;
			}
			set
			{
				if ((this._IsCollapsed != value))
				{
					this.OnIsCollapsedChanging(value);
					this.SendPropertyChanging();
					this._IsCollapsed = value;
					this.SendPropertyChanged("IsCollapsed");
					this.OnIsCollapsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblyName", DbType="NVarChar(50)")]
		public string AssemblyName
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this.OnAssemblyNameChanging(value);
					this.SendPropertyChanging();
					this._AssemblyName = value;
					this.SendPropertyChanged("AssemblyName");
					this.OnAssemblyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortcutKeys", DbType="VarChar(20)")]
		public string ShortcutKeys
		{
			get
			{
				return this._ShortcutKeys;
			}
			set
			{
				if ((this._ShortcutKeys != value))
				{
					this.OnShortcutKeysChanging(value);
					this.SendPropertyChanging();
					this._ShortcutKeys = value;
					this.SendPropertyChanged("ShortcutKeys");
					this.OnShortcutKeysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupperAdmin", DbType="Bit")]
		public System.Nullable<bool> SupperAdmin
		{
			get
			{
				return this._SupperAdmin;
			}
			set
			{
				if ((this._SupperAdmin != value))
				{
					this.OnSupperAdminChanging(value);
					this.SendPropertyChanging();
					this._SupperAdmin = value;
					this.SendPropertyChanged("SupperAdmin");
					this.OnSupperAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMD_Message")]
	public partial class tblMD_Message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MessageID;
		
		private string _Language;
		
		private string _Content;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIDChanging(string value);
    partial void OnMessageIDChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    #endregion
		
		public tblMD_Message()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				if ((this._MessageID != value))
				{
					this.OnMessageIDChanging(value);
					this.SendPropertyChanging();
					this._MessageID = value;
					this.SendPropertyChanged("MessageID");
					this.OnMessageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDepartment")]
	public partial class tblDepartment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DepartmentID;
		
		private int _DivisionID;
		
		private string _DepartmentCode;
		
		private string _DepartmentName;
		
		private System.Nullable<int> _Foreigner;
		
		private string _JapaneseName;
		
		private string _VietnameseName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepartmentIDChanging(int value);
    partial void OnDepartmentIDChanged();
    partial void OnDivisionIDChanging(int value);
    partial void OnDivisionIDChanged();
    partial void OnDepartmentCodeChanging(string value);
    partial void OnDepartmentCodeChanged();
    partial void OnDepartmentNameChanging(string value);
    partial void OnDepartmentNameChanged();
    partial void OnForeignerChanging(System.Nullable<int> value);
    partial void OnForeignerChanged();
    partial void OnJapaneseNameChanging(string value);
    partial void OnJapaneseNameChanged();
    partial void OnVietnameseNameChanging(string value);
    partial void OnVietnameseNameChanged();
    #endregion
		
		public tblDepartment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionID", DbType="Int NOT NULL")]
		public int DivisionID
		{
			get
			{
				return this._DivisionID;
			}
			set
			{
				if ((this._DivisionID != value))
				{
					this.OnDivisionIDChanging(value);
					this.SendPropertyChanging();
					this._DivisionID = value;
					this.SendPropertyChanged("DivisionID");
					this.OnDivisionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DepartmentCode
		{
			get
			{
				return this._DepartmentCode;
			}
			set
			{
				if ((this._DepartmentCode != value))
				{
					this.OnDepartmentCodeChanging(value);
					this.SendPropertyChanging();
					this._DepartmentCode = value;
					this.SendPropertyChanged("DepartmentCode");
					this.OnDepartmentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(200)")]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this.OnDepartmentNameChanging(value);
					this.SendPropertyChanging();
					this._DepartmentName = value;
					this.SendPropertyChanged("DepartmentName");
					this.OnDepartmentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreigner", DbType="Int")]
		public System.Nullable<int> Foreigner
		{
			get
			{
				return this._Foreigner;
			}
			set
			{
				if ((this._Foreigner != value))
				{
					this.OnForeignerChanging(value);
					this.SendPropertyChanging();
					this._Foreigner = value;
					this.SendPropertyChanged("Foreigner");
					this.OnForeignerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JapaneseName", DbType="NVarChar(200)")]
		public string JapaneseName
		{
			get
			{
				return this._JapaneseName;
			}
			set
			{
				if ((this._JapaneseName != value))
				{
					this.OnJapaneseNameChanging(value);
					this.SendPropertyChanging();
					this._JapaneseName = value;
					this.SendPropertyChanged("JapaneseName");
					this.OnJapaneseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietnameseName", DbType="NVarChar(200)")]
		public string VietnameseName
		{
			get
			{
				return this._VietnameseName;
			}
			set
			{
				if ((this._VietnameseName != value))
				{
					this.OnVietnameseNameChanging(value);
					this.SendPropertyChanging();
					this._VietnameseName = value;
					this.SendPropertyChanged("VietnameseName");
					this.OnVietnameseNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDivision")]
	public partial class tblDivision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DivisionID;
		
		private string _DivisionCode;
		
		private string _DivisionName;
		
		private System.Nullable<int> _BranchID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDivisionIDChanging(int value);
    partial void OnDivisionIDChanged();
    partial void OnDivisionCodeChanging(string value);
    partial void OnDivisionCodeChanged();
    partial void OnDivisionNameChanging(string value);
    partial void OnDivisionNameChanged();
    partial void OnBranchIDChanging(System.Nullable<int> value);
    partial void OnBranchIDChanged();
    #endregion
		
		public tblDivision()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DivisionID
		{
			get
			{
				return this._DivisionID;
			}
			set
			{
				if ((this._DivisionID != value))
				{
					this.OnDivisionIDChanging(value);
					this.SendPropertyChanging();
					this._DivisionID = value;
					this.SendPropertyChanged("DivisionID");
					this.OnDivisionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DivisionCode
		{
			get
			{
				return this._DivisionCode;
			}
			set
			{
				if ((this._DivisionCode != value))
				{
					this.OnDivisionCodeChanging(value);
					this.SendPropertyChanging();
					this._DivisionCode = value;
					this.SendPropertyChanged("DivisionCode");
					this.OnDivisionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionName", DbType="NVarChar(100)")]
		public string DivisionName
		{
			get
			{
				return this._DivisionName;
			}
			set
			{
				if ((this._DivisionName != value))
				{
					this.OnDivisionNameChanging(value);
					this.SendPropertyChanging();
					this._DivisionName = value;
					this.SendPropertyChanged("DivisionName");
					this.OnDivisionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchID", DbType="Int")]
		public System.Nullable<int> BranchID
		{
			get
			{
				return this._BranchID;
			}
			set
			{
				if ((this._BranchID != value))
				{
					this.OnBranchIDChanging(value);
					this.SendPropertyChanging();
					this._BranchID = value;
					this.SendPropertyChanged("BranchID");
					this.OnBranchIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCompany")]
	public partial class tblCompany : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CompanyID;
		
		private string _CompanyFullName;
		
		private string _CompanyFullNameEN;
		
		private string _ComAcronymName;
		
		private string _DirectorName;
		
		private string _PhoneNumber;
		
		private string _FaxNumber;
		
		private string _BankAccount;
		
		private string _Address;
		
		private string _AddressEN;
		
		private string _TaxRegNo;
		
		private System.Nullable<System.DateTime> _TaxRegDate;
		
		private System.Data.Linq.Binary _Logo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyIDChanging(int value);
    partial void OnCompanyIDChanged();
    partial void OnCompanyFullNameChanging(string value);
    partial void OnCompanyFullNameChanged();
    partial void OnCompanyFullNameENChanging(string value);
    partial void OnCompanyFullNameENChanged();
    partial void OnComAcronymNameChanging(string value);
    partial void OnComAcronymNameChanged();
    partial void OnDirectorNameChanging(string value);
    partial void OnDirectorNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnBankAccountChanging(string value);
    partial void OnBankAccountChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddressENChanging(string value);
    partial void OnAddressENChanged();
    partial void OnTaxRegNoChanging(string value);
    partial void OnTaxRegNoChanged();
    partial void OnTaxRegDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTaxRegDateChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    #endregion
		
		public tblCompany()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyFullName", DbType="NVarChar(100)")]
		public string CompanyFullName
		{
			get
			{
				return this._CompanyFullName;
			}
			set
			{
				if ((this._CompanyFullName != value))
				{
					this.OnCompanyFullNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyFullName = value;
					this.SendPropertyChanged("CompanyFullName");
					this.OnCompanyFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyFullNameEN", DbType="NVarChar(100)")]
		public string CompanyFullNameEN
		{
			get
			{
				return this._CompanyFullNameEN;
			}
			set
			{
				if ((this._CompanyFullNameEN != value))
				{
					this.OnCompanyFullNameENChanging(value);
					this.SendPropertyChanging();
					this._CompanyFullNameEN = value;
					this.SendPropertyChanged("CompanyFullNameEN");
					this.OnCompanyFullNameENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComAcronymName", DbType="VarChar(20)")]
		public string ComAcronymName
		{
			get
			{
				return this._ComAcronymName;
			}
			set
			{
				if ((this._ComAcronymName != value))
				{
					this.OnComAcronymNameChanging(value);
					this.SendPropertyChanging();
					this._ComAcronymName = value;
					this.SendPropertyChanged("ComAcronymName");
					this.OnComAcronymNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectorName", DbType="NVarChar(50)")]
		public string DirectorName
		{
			get
			{
				return this._DirectorName;
			}
			set
			{
				if ((this._DirectorName != value))
				{
					this.OnDirectorNameChanging(value);
					this.SendPropertyChanging();
					this._DirectorName = value;
					this.SendPropertyChanged("DirectorName");
					this.OnDirectorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="VarChar(20)")]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccount", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BankAccount
		{
			get
			{
				return this._BankAccount;
			}
			set
			{
				if ((this._BankAccount != value))
				{
					this.OnBankAccountChanging(value);
					this.SendPropertyChanging();
					this._BankAccount = value;
					this.SendPropertyChanged("BankAccount");
					this.OnBankAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressEN", DbType="NVarChar(100)")]
		public string AddressEN
		{
			get
			{
				return this._AddressEN;
			}
			set
			{
				if ((this._AddressEN != value))
				{
					this.OnAddressENChanging(value);
					this.SendPropertyChanging();
					this._AddressEN = value;
					this.SendPropertyChanged("AddressEN");
					this.OnAddressENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRegNo", DbType="VarChar(20)")]
		public string TaxRegNo
		{
			get
			{
				return this._TaxRegNo;
			}
			set
			{
				if ((this._TaxRegNo != value))
				{
					this.OnTaxRegNoChanging(value);
					this.SendPropertyChanging();
					this._TaxRegNo = value;
					this.SendPropertyChanged("TaxRegNo");
					this.OnTaxRegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRegDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TaxRegDate
		{
			get
			{
				return this._TaxRegDate;
			}
			set
			{
				if ((this._TaxRegDate != value))
				{
					this.OnTaxRegDateChanging(value);
					this.SendPropertyChanging();
					this._TaxRegDate = value;
					this.SendPropertyChanged("TaxRegDate");
					this.OnTaxRegDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGroup")]
	public partial class tblGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GroupID;
		
		private System.Nullable<int> _SectionID;
		
		private string _GroupCode;
		
		private string _GroupName;
		
		private string _JapaneseName;
		
		private string _VietnameseName;
		
		private System.Nullable<int> _Foreigner;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnSectionIDChanging(System.Nullable<int> value);
    partial void OnSectionIDChanged();
    partial void OnGroupCodeChanging(string value);
    partial void OnGroupCodeChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnJapaneseNameChanging(string value);
    partial void OnJapaneseNameChanged();
    partial void OnVietnameseNameChanging(string value);
    partial void OnVietnameseNameChanged();
    partial void OnForeignerChanging(System.Nullable<int> value);
    partial void OnForeignerChanged();
    #endregion
		
		public tblGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionID", DbType="Int")]
		public System.Nullable<int> SectionID
		{
			get
			{
				return this._SectionID;
			}
			set
			{
				if ((this._SectionID != value))
				{
					this.OnSectionIDChanging(value);
					this.SendPropertyChanging();
					this._SectionID = value;
					this.SendPropertyChanged("SectionID");
					this.OnSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(100)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JapaneseName", DbType="NVarChar(100)")]
		public string JapaneseName
		{
			get
			{
				return this._JapaneseName;
			}
			set
			{
				if ((this._JapaneseName != value))
				{
					this.OnJapaneseNameChanging(value);
					this.SendPropertyChanging();
					this._JapaneseName = value;
					this.SendPropertyChanged("JapaneseName");
					this.OnJapaneseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietnameseName", DbType="NVarChar(100)")]
		public string VietnameseName
		{
			get
			{
				return this._VietnameseName;
			}
			set
			{
				if ((this._VietnameseName != value))
				{
					this.OnVietnameseNameChanging(value);
					this.SendPropertyChanging();
					this._VietnameseName = value;
					this.SendPropertyChanged("VietnameseName");
					this.OnVietnameseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreigner", DbType="Int")]
		public System.Nullable<int> Foreigner
		{
			get
			{
				return this._Foreigner;
			}
			set
			{
				if ((this._Foreigner != value))
				{
					this.OnForeignerChanging(value);
					this.SendPropertyChanging();
					this._Foreigner = value;
					this.SendPropertyChanged("Foreigner");
					this.OnForeignerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSection")]
	public partial class tblSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SectionID;
		
		private int _DepartmentID;
		
		private string _SectionCode;
		
		private string _SectionName;
		
		private string _JapaneseName;
		
		private string _VietnameseName;
		
		private System.Nullable<int> _Foreigner;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionIDChanging(int value);
    partial void OnSectionIDChanged();
    partial void OnDepartmentIDChanging(int value);
    partial void OnDepartmentIDChanged();
    partial void OnSectionCodeChanging(string value);
    partial void OnSectionCodeChanged();
    partial void OnSectionNameChanging(string value);
    partial void OnSectionNameChanged();
    partial void OnJapaneseNameChanging(string value);
    partial void OnJapaneseNameChanged();
    partial void OnVietnameseNameChanging(string value);
    partial void OnVietnameseNameChanged();
    partial void OnForeignerChanging(System.Nullable<int> value);
    partial void OnForeignerChanged();
    #endregion
		
		public tblSection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SectionID
		{
			get
			{
				return this._SectionID;
			}
			set
			{
				if ((this._SectionID != value))
				{
					this.OnSectionIDChanging(value);
					this.SendPropertyChanging();
					this._SectionID = value;
					this.SendPropertyChanged("SectionID");
					this.OnSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int NOT NULL")]
		public int DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SectionCode
		{
			get
			{
				return this._SectionCode;
			}
			set
			{
				if ((this._SectionCode != value))
				{
					this.OnSectionCodeChanging(value);
					this.SendPropertyChanging();
					this._SectionCode = value;
					this.SendPropertyChanged("SectionCode");
					this.OnSectionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionName", DbType="NVarChar(100)")]
		public string SectionName
		{
			get
			{
				return this._SectionName;
			}
			set
			{
				if ((this._SectionName != value))
				{
					this.OnSectionNameChanging(value);
					this.SendPropertyChanging();
					this._SectionName = value;
					this.SendPropertyChanged("SectionName");
					this.OnSectionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JapaneseName", DbType="NVarChar(100)")]
		public string JapaneseName
		{
			get
			{
				return this._JapaneseName;
			}
			set
			{
				if ((this._JapaneseName != value))
				{
					this.OnJapaneseNameChanging(value);
					this.SendPropertyChanging();
					this._JapaneseName = value;
					this.SendPropertyChanged("JapaneseName");
					this.OnJapaneseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietnameseName", DbType="NVarChar(100)")]
		public string VietnameseName
		{
			get
			{
				return this._VietnameseName;
			}
			set
			{
				if ((this._VietnameseName != value))
				{
					this.OnVietnameseNameChanging(value);
					this.SendPropertyChanging();
					this._VietnameseName = value;
					this.SendPropertyChanged("VietnameseName");
					this.OnVietnameseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreigner", DbType="Int")]
		public System.Nullable<int> Foreigner
		{
			get
			{
				return this._Foreigner;
			}
			set
			{
				if ((this._Foreigner != value))
				{
					this.OnForeignerChanging(value);
					this.SendPropertyChanging();
					this._Foreigner = value;
					this.SendPropertyChanged("Foreigner");
					this.OnForeignerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
