<?xml version="1.0" encoding="utf-8"?><Database Name="phanmemtinhluon_P4" Class="DataDaigramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=112.78.2.166,1455;Initial Catalog=phanmemtinhluon_P4;Persist Security Info=True;User ID=phanmemtinhluon_saP4" SettingsObjectName="HPA.SQL.Properties.Settings" SettingsPropertyName="phanmemtinhluon_P4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblSC_Login" Member="tblSC_Logins">
    <Type Name="tblSC_Login">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminRight" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LastChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DivisionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEN_Menu" Member="MEN_Menus">
    <Type Name="MEN_Menu">
      <Column Name="MenuID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsModal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LinkMenuID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsCollapsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShortcutKeys" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SupperAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SC_Login_CheckLogin" Method="SC_Login_CheckLogin">
    <Parameter Name="LoginName" Parameter="loginName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Message" Method="Get_Message">
    <Parameter Name="MessageID" Parameter="messageID" Type="System.String" DbType="Char(50)" />
    <Parameter Name="Language" Parameter="language" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SC_USEROBJECTRIGHT_GET" Method="SC_USEROBJECTRIGHT_GET">
    <Parameter Name="p_FullClassName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="p_LoginID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>