//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Paradise5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginLogin(Paradise5.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.LoginResponse EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Checklogin", ReplyAction="http://tempuri.org/IService1/CheckloginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginChecklogin(Paradise5.ServiceReference1.CheckloginRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.CheckloginResponse EndChecklogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetSession", ReplyAction="http://tempuri.org/IService1/SetSessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSetSession(Paradise5.ServiceReference1.SetSessionRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.SetSessionResponse EndSetSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSession", ReplyAction="http://tempuri.org/IService1/GetSessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetSession(Paradise5.ServiceReference1.GetSessionRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.GetSessionResponse EndGetSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RemoveSession", ReplyAction="http://tempuri.org/IService1/RemoveSessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRemoveSession(System.AsyncCallback callback, object asyncState);
        
        void EndRemoveSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetMenu", ReplyAction="http://tempuri.org/IService1/GetMenuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetMenu(Paradise5.ServiceReference1.GetMenuRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.GetMenuResponse EndGetMenu(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ViewMN", ReplyAction="http://tempuri.org/IService1/ViewMNResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginViewMN(Paradise5.ServiceReference1.ViewMNRequest request, System.AsyncCallback callback, object asyncState);
        
        Paradise5.ServiceReference1.ViewMNResponse EndViewMN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetID", ReplyAction="http://tempuri.org/IService1/GetIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetID(System.AsyncCallback callback, object asyncState);
        
        int EndGetID(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class tblSC_Login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int loginIDField;
        
        private bool loginIDFieldSpecified;
        
        private string loginNameField;
        
        private string passWordField;
        
        private string employeeIDField;
        
        private System.Nullable<int> departmentIDField;
        
        private bool departmentIDFieldSpecified;
        
        private System.Nullable<byte> adminRightField;
        
        private bool adminRightFieldSpecified;
        
        private System.Nullable<System.DateTime> lastChangedDateField;
        
        private bool lastChangedDateFieldSpecified;
        
        private System.Nullable<int> divisionIDField;
        
        private bool divisionIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
                this.RaisePropertyChanged("LoginID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoginIDSpecified {
            get {
                return this.loginIDFieldSpecified;
            }
            set {
                this.loginIDFieldSpecified = value;
                this.RaisePropertyChanged("LoginIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
                this.RaisePropertyChanged("LoginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
                this.RaisePropertyChanged("DepartmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepartmentIDSpecified {
            get {
                return this.departmentIDFieldSpecified;
            }
            set {
                this.departmentIDFieldSpecified = value;
                this.RaisePropertyChanged("DepartmentIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<byte> AdminRight {
            get {
                return this.adminRightField;
            }
            set {
                this.adminRightField = value;
                this.RaisePropertyChanged("AdminRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdminRightSpecified {
            get {
                return this.adminRightFieldSpecified;
            }
            set {
                this.adminRightFieldSpecified = value;
                this.RaisePropertyChanged("AdminRightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> LastChangedDate {
            get {
                return this.lastChangedDateField;
            }
            set {
                this.lastChangedDateField = value;
                this.RaisePropertyChanged("LastChangedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastChangedDateSpecified {
            get {
                return this.lastChangedDateFieldSpecified;
            }
            set {
                this.lastChangedDateFieldSpecified = value;
                this.RaisePropertyChanged("LastChangedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> DivisionID {
            get {
                return this.divisionIDField;
            }
            set {
                this.divisionIDField = value;
                this.RaisePropertyChanged("DivisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DivisionIDSpecified {
            get {
                return this.divisionIDFieldSpecified;
            }
            set {
                this.divisionIDFieldSpecified = value;
                this.RaisePropertyChanged("DivisionIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class ViewMenu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string menuIDField;
        
        private string nameField;
        
        private string classNameField;
        
        private System.Nullable<int> priorityField;
        
        private bool priorityFieldSpecified;
        
        private string parentMenuIDField;
        
        private string assemblyNameField;
        
        private System.Nullable<bool> isModalField;
        
        private bool isModalFieldSpecified;
        
        private System.Nullable<bool> isCollapsedField;
        
        private bool isCollapsedFieldSpecified;
        
        private string shortcutKeysField;
        
        private string languageField;
        
        private System.Nullable<bool> isVisibleField;
        
        private bool isVisibleFieldSpecified;
        
        private int accessField;
        
        private bool accessFieldSpecified;
        
        private System.Nullable<bool> supperAdminField;
        
        private bool supperAdminFieldSpecified;
        
        private int loginIDField;
        
        private bool loginIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string MenuID {
            get {
                return this.menuIDField;
            }
            set {
                this.menuIDField = value;
                this.RaisePropertyChanged("MenuID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
                this.RaisePropertyChanged("PrioritySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ParentMenuID {
            get {
                return this.parentMenuIDField;
            }
            set {
                this.parentMenuIDField = value;
                this.RaisePropertyChanged("ParentMenuID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
                this.RaisePropertyChanged("AssemblyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> IsModal {
            get {
                return this.isModalField;
            }
            set {
                this.isModalField = value;
                this.RaisePropertyChanged("IsModal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsModalSpecified {
            get {
                return this.isModalFieldSpecified;
            }
            set {
                this.isModalFieldSpecified = value;
                this.RaisePropertyChanged("IsModalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsCollapsed {
            get {
                return this.isCollapsedField;
            }
            set {
                this.isCollapsedField = value;
                this.RaisePropertyChanged("IsCollapsed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCollapsedSpecified {
            get {
                return this.isCollapsedFieldSpecified;
            }
            set {
                this.isCollapsedFieldSpecified = value;
                this.RaisePropertyChanged("IsCollapsedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ShortcutKeys {
            get {
                return this.shortcutKeysField;
            }
            set {
                this.shortcutKeysField = value;
                this.RaisePropertyChanged("ShortcutKeys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<bool> IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
                this.RaisePropertyChanged("IsVisible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsVisibleSpecified {
            get {
                return this.isVisibleFieldSpecified;
            }
            set {
                this.isVisibleFieldSpecified = value;
                this.RaisePropertyChanged("IsVisibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
                this.RaisePropertyChanged("Access");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessSpecified {
            get {
                return this.accessFieldSpecified;
            }
            set {
                this.accessFieldSpecified = value;
                this.RaisePropertyChanged("AccessSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<bool> SupperAdmin {
            get {
                return this.supperAdminField;
            }
            set {
                this.supperAdminField = value;
                this.RaisePropertyChanged("SupperAdmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupperAdminSpecified {
            get {
                return this.supperAdminFieldSpecified;
            }
            set {
                this.supperAdminFieldSpecified = value;
                this.RaisePropertyChanged("SupperAdminSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
                this.RaisePropertyChanged("LoginID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LoginIDSpecified {
            get {
                return this.loginIDFieldSpecified;
            }
            set {
                this.loginIDFieldSpecified = value;
                this.RaisePropertyChanged("LoginIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        public LoginRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
        public Paradise5.ServiceReference1.tblSC_Login[] LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Paradise5.ServiceReference1.tblSC_Login[] LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Checklogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckloginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pass;
        
        public CheckloginRequest() {
        }
        
        public CheckloginRequest(string Name, string Pass) {
            this.Name = Name;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckloginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckloginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CheckloginResult;
        
        public CheckloginResponse() {
        }
        
        public CheckloginResponse(int CheckloginResult) {
            this.CheckloginResult = CheckloginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSession", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        public SetSessionRequest() {
        }
        
        public SetSessionRequest(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSessionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetSessionResponse {
        
        public SetSessionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSession", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSessionRequest {
        
        public GetSessionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSessionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetSessionResult;
        
        public GetSessionResponse() {
        }
        
        public GetSessionResponse(string GetSessionResult) {
            this.GetSessionResult = GetSessionResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetMenuResponseGetMenuResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
                this.RaisePropertyChanged("Any1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuRequest {
        
        public GetMenuRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Paradise5.ServiceReference1.GetMenuResponseGetMenuResult GetMenuResult;
        
        public GetMenuResponse() {
        }
        
        public GetMenuResponse(Paradise5.ServiceReference1.GetMenuResponseGetMenuResult GetMenuResult) {
            this.GetMenuResult = GetMenuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ViewMN", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ViewMNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Langgue;
        
        public ViewMNRequest() {
        }
        
        public ViewMNRequest(string Langgue) {
            this.Langgue = Langgue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ViewMNResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ViewMNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
        public Paradise5.ServiceReference1.ViewMenu[] ViewMNResult;
        
        public ViewMNResponse() {
        }
        
        public ViewMNResponse(Paradise5.ServiceReference1.ViewMenu[] ViewMNResult) {
            this.ViewMNResult = ViewMNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Paradise5.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Paradise5.ServiceReference1.tblSC_Login[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Paradise5.ServiceReference1.tblSC_Login[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Paradise5.ServiceReference1.GetMenuResponseGetMenuResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Paradise5.ServiceReference1.GetMenuResponseGetMenuResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewMNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ViewMNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Paradise5.ServiceReference1.ViewMenu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Paradise5.ServiceReference1.ViewMenu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Paradise5.ServiceReference1.IService1>, Paradise5.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckloginDelegate;
        
        private EndOperationDelegate onEndCheckloginDelegate;
        
        private System.Threading.SendOrPostCallback onCheckloginCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetSessionDelegate;
        
        private EndOperationDelegate onEndSetSessionDelegate;
        
        private System.Threading.SendOrPostCallback onSetSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSessionDelegate;
        
        private EndOperationDelegate onEndGetSessionDelegate;
        
        private System.Threading.SendOrPostCallback onGetSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveSessionDelegate;
        
        private EndOperationDelegate onEndRemoveSessionDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuDelegate;
        
        private EndOperationDelegate onEndGetMenuDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuCompletedDelegate;
        
        private BeginOperationDelegate onBeginViewMNDelegate;
        
        private EndOperationDelegate onEndViewMNDelegate;
        
        private System.Threading.SendOrPostCallback onViewMNCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetIDDelegate;
        
        private EndOperationDelegate onEndGetIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<CheckloginCompletedEventArgs> CheckloginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetSessionCompleted;
        
        public event System.EventHandler<GetSessionCompletedEventArgs> GetSessionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RemoveSessionCompleted;
        
        public event System.EventHandler<GetMenuCompletedEventArgs> GetMenuCompleted;
        
        public event System.EventHandler<ViewMNCompletedEventArgs> ViewMNCompleted;
        
        public event System.EventHandler<GetIDCompletedEventArgs> GetIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginLogin(Paradise5.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogin(System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.LoginRequest inValue = new Paradise5.ServiceReference1.LoginRequest();
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.LoginResponse Paradise5.ServiceReference1.IService1.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Paradise5.ServiceReference1.tblSC_Login[] EndLogin(System.IAsyncResult result) {
            Paradise5.ServiceReference1.LoginResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndLogin(result);
            return retVal.LoginResult;
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginLogin(callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            Paradise5.ServiceReference1.tblSC_Login[] retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync() {
            this.LoginAsync(null);
        }
        
        public void LoginAsync(object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, null, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginChecklogin(Paradise5.ServiceReference1.CheckloginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChecklogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginChecklogin(string Name, string Pass, System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.CheckloginRequest inValue = new Paradise5.ServiceReference1.CheckloginRequest();
            inValue.Name = Name;
            inValue.Pass = Pass;
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginChecklogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.CheckloginResponse Paradise5.ServiceReference1.IService1.EndChecklogin(System.IAsyncResult result) {
            return base.Channel.EndChecklogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int EndChecklogin(System.IAsyncResult result) {
            Paradise5.ServiceReference1.CheckloginResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndChecklogin(result);
            return retVal.CheckloginResult;
        }
        
        private System.IAsyncResult OnBeginChecklogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Name = ((string)(inValues[0]));
            string Pass = ((string)(inValues[1]));
            return this.BeginChecklogin(Name, Pass, callback, asyncState);
        }
        
        private object[] OnEndChecklogin(System.IAsyncResult result) {
            int retVal = this.EndChecklogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckloginCompleted(object state) {
            if ((this.CheckloginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckloginCompleted(this, new CheckloginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckloginAsync(string Name, string Pass) {
            this.CheckloginAsync(Name, Pass, null);
        }
        
        public void CheckloginAsync(string Name, string Pass, object userState) {
            if ((this.onBeginCheckloginDelegate == null)) {
                this.onBeginCheckloginDelegate = new BeginOperationDelegate(this.OnBeginChecklogin);
            }
            if ((this.onEndCheckloginDelegate == null)) {
                this.onEndCheckloginDelegate = new EndOperationDelegate(this.OnEndChecklogin);
            }
            if ((this.onCheckloginCompletedDelegate == null)) {
                this.onCheckloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckloginCompleted);
            }
            base.InvokeAsync(this.onBeginCheckloginDelegate, new object[] {
                        Name,
                        Pass}, this.onEndCheckloginDelegate, this.onCheckloginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginSetSession(Paradise5.ServiceReference1.SetSessionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetSession(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSetSession(string UserName, System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.SetSessionRequest inValue = new Paradise5.ServiceReference1.SetSessionRequest();
            inValue.UserName = UserName;
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginSetSession(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.SetSessionResponse Paradise5.ServiceReference1.IService1.EndSetSession(System.IAsyncResult result) {
            return base.Channel.EndSetSession(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndSetSession(System.IAsyncResult result) {
            Paradise5.ServiceReference1.SetSessionResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndSetSession(result);
        }
        
        private System.IAsyncResult OnBeginSetSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string UserName = ((string)(inValues[0]));
            return this.BeginSetSession(UserName, callback, asyncState);
        }
        
        private object[] OnEndSetSession(System.IAsyncResult result) {
            this.EndSetSession(result);
            return null;
        }
        
        private void OnSetSessionCompleted(object state) {
            if ((this.SetSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetSessionAsync(string UserName) {
            this.SetSessionAsync(UserName, null);
        }
        
        public void SetSessionAsync(string UserName, object userState) {
            if ((this.onBeginSetSessionDelegate == null)) {
                this.onBeginSetSessionDelegate = new BeginOperationDelegate(this.OnBeginSetSession);
            }
            if ((this.onEndSetSessionDelegate == null)) {
                this.onEndSetSessionDelegate = new EndOperationDelegate(this.OnEndSetSession);
            }
            if ((this.onSetSessionCompletedDelegate == null)) {
                this.onSetSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetSessionCompleted);
            }
            base.InvokeAsync(this.onBeginSetSessionDelegate, new object[] {
                        UserName}, this.onEndSetSessionDelegate, this.onSetSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginGetSession(Paradise5.ServiceReference1.GetSessionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSession(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSession(System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.GetSessionRequest inValue = new Paradise5.ServiceReference1.GetSessionRequest();
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginGetSession(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.GetSessionResponse Paradise5.ServiceReference1.IService1.EndGetSession(System.IAsyncResult result) {
            return base.Channel.EndGetSession(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetSession(System.IAsyncResult result) {
            Paradise5.ServiceReference1.GetSessionResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndGetSession(result);
            return retVal.GetSessionResult;
        }
        
        private System.IAsyncResult OnBeginGetSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSession(callback, asyncState);
        }
        
        private object[] OnEndGetSession(System.IAsyncResult result) {
            string retVal = this.EndGetSession(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSessionCompleted(object state) {
            if ((this.GetSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSessionCompleted(this, new GetSessionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSessionAsync() {
            this.GetSessionAsync(null);
        }
        
        public void GetSessionAsync(object userState) {
            if ((this.onBeginGetSessionDelegate == null)) {
                this.onBeginGetSessionDelegate = new BeginOperationDelegate(this.OnBeginGetSession);
            }
            if ((this.onEndGetSessionDelegate == null)) {
                this.onEndGetSessionDelegate = new EndOperationDelegate(this.OnEndGetSession);
            }
            if ((this.onGetSessionCompletedDelegate == null)) {
                this.onGetSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSessionCompleted);
            }
            base.InvokeAsync(this.onBeginGetSessionDelegate, null, this.onEndGetSessionDelegate, this.onGetSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginRemoveSession(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveSession(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Paradise5.ServiceReference1.IService1.EndRemoveSession(System.IAsyncResult result) {
            base.Channel.EndRemoveSession(result);
        }
        
        private System.IAsyncResult OnBeginRemoveSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginRemoveSession(callback, asyncState);
        }
        
        private object[] OnEndRemoveSession(System.IAsyncResult result) {
            ((Paradise5.ServiceReference1.IService1)(this)).EndRemoveSession(result);
            return null;
        }
        
        private void OnRemoveSessionCompleted(object state) {
            if ((this.RemoveSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveSessionAsync() {
            this.RemoveSessionAsync(null);
        }
        
        public void RemoveSessionAsync(object userState) {
            if ((this.onBeginRemoveSessionDelegate == null)) {
                this.onBeginRemoveSessionDelegate = new BeginOperationDelegate(this.OnBeginRemoveSession);
            }
            if ((this.onEndRemoveSessionDelegate == null)) {
                this.onEndRemoveSessionDelegate = new EndOperationDelegate(this.OnEndRemoveSession);
            }
            if ((this.onRemoveSessionCompletedDelegate == null)) {
                this.onRemoveSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveSessionCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveSessionDelegate, null, this.onEndRemoveSessionDelegate, this.onRemoveSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginGetMenu(Paradise5.ServiceReference1.GetMenuRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenu(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetMenu(System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.GetMenuRequest inValue = new Paradise5.ServiceReference1.GetMenuRequest();
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginGetMenu(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.GetMenuResponse Paradise5.ServiceReference1.IService1.EndGetMenu(System.IAsyncResult result) {
            return base.Channel.EndGetMenu(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Paradise5.ServiceReference1.GetMenuResponseGetMenuResult EndGetMenu(System.IAsyncResult result) {
            Paradise5.ServiceReference1.GetMenuResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndGetMenu(result);
            return retVal.GetMenuResult;
        }
        
        private System.IAsyncResult OnBeginGetMenu(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMenu(callback, asyncState);
        }
        
        private object[] OnEndGetMenu(System.IAsyncResult result) {
            Paradise5.ServiceReference1.GetMenuResponseGetMenuResult retVal = this.EndGetMenu(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuCompleted(object state) {
            if ((this.GetMenuCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuCompleted(this, new GetMenuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuAsync() {
            this.GetMenuAsync(null);
        }
        
        public void GetMenuAsync(object userState) {
            if ((this.onBeginGetMenuDelegate == null)) {
                this.onBeginGetMenuDelegate = new BeginOperationDelegate(this.OnBeginGetMenu);
            }
            if ((this.onEndGetMenuDelegate == null)) {
                this.onEndGetMenuDelegate = new EndOperationDelegate(this.OnEndGetMenu);
            }
            if ((this.onGetMenuCompletedDelegate == null)) {
                this.onGetMenuCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuDelegate, null, this.onEndGetMenuDelegate, this.onGetMenuCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginViewMN(Paradise5.ServiceReference1.ViewMNRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginViewMN(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginViewMN(string Langgue, System.AsyncCallback callback, object asyncState) {
            Paradise5.ServiceReference1.ViewMNRequest inValue = new Paradise5.ServiceReference1.ViewMNRequest();
            inValue.Langgue = Langgue;
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginViewMN(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paradise5.ServiceReference1.ViewMNResponse Paradise5.ServiceReference1.IService1.EndViewMN(System.IAsyncResult result) {
            return base.Channel.EndViewMN(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Paradise5.ServiceReference1.ViewMenu[] EndViewMN(System.IAsyncResult result) {
            Paradise5.ServiceReference1.ViewMNResponse retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndViewMN(result);
            return retVal.ViewMNResult;
        }
        
        private System.IAsyncResult OnBeginViewMN(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Langgue = ((string)(inValues[0]));
            return this.BeginViewMN(Langgue, callback, asyncState);
        }
        
        private object[] OnEndViewMN(System.IAsyncResult result) {
            Paradise5.ServiceReference1.ViewMenu[] retVal = this.EndViewMN(result);
            return new object[] {
                    retVal};
        }
        
        private void OnViewMNCompleted(object state) {
            if ((this.ViewMNCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ViewMNCompleted(this, new ViewMNCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ViewMNAsync(string Langgue) {
            this.ViewMNAsync(Langgue, null);
        }
        
        public void ViewMNAsync(string Langgue, object userState) {
            if ((this.onBeginViewMNDelegate == null)) {
                this.onBeginViewMNDelegate = new BeginOperationDelegate(this.OnBeginViewMN);
            }
            if ((this.onEndViewMNDelegate == null)) {
                this.onEndViewMNDelegate = new EndOperationDelegate(this.OnEndViewMN);
            }
            if ((this.onViewMNCompletedDelegate == null)) {
                this.onViewMNCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnViewMNCompleted);
            }
            base.InvokeAsync(this.onBeginViewMNDelegate, new object[] {
                        Langgue}, this.onEndViewMNDelegate, this.onViewMNCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginGetID(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetID(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Paradise5.ServiceReference1.IService1.EndGetID(System.IAsyncResult result) {
            return base.Channel.EndGetID(result);
        }
        
        private System.IAsyncResult OnBeginGetID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginGetID(callback, asyncState);
        }
        
        private object[] OnEndGetID(System.IAsyncResult result) {
            int retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndGetID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetIDCompleted(object state) {
            if ((this.GetIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetIDCompleted(this, new GetIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetIDAsync() {
            this.GetIDAsync(null);
        }
        
        public void GetIDAsync(object userState) {
            if ((this.onBeginGetIDDelegate == null)) {
                this.onBeginGetIDDelegate = new BeginOperationDelegate(this.OnBeginGetID);
            }
            if ((this.onEndGetIDDelegate == null)) {
                this.onEndGetIDDelegate = new EndOperationDelegate(this.OnEndGetID);
            }
            if ((this.onGetIDCompletedDelegate == null)) {
                this.onGetIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetIDDelegate, null, this.onEndGetIDDelegate, this.onGetIDCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Paradise5.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Paradise5.ServiceReference1.IService1>, Paradise5.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Paradise5.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(Paradise5.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.LoginResponse EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.LoginResponse _result = ((Paradise5.ServiceReference1.LoginResponse)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChecklogin(Paradise5.ServiceReference1.CheckloginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Checklogin", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.CheckloginResponse EndChecklogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.CheckloginResponse _result = ((Paradise5.ServiceReference1.CheckloginResponse)(base.EndInvoke("Checklogin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetSession(Paradise5.ServiceReference1.SetSessionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SetSession", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.SetSessionResponse EndSetSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.SetSessionResponse _result = ((Paradise5.ServiceReference1.SetSessionResponse)(base.EndInvoke("SetSession", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSession(Paradise5.ServiceReference1.GetSessionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSession", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.GetSessionResponse EndGetSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.GetSessionResponse _result = ((Paradise5.ServiceReference1.GetSessionResponse)(base.EndInvoke("GetSession", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemoveSession(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RemoveSession", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRemoveSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RemoveSession", _args, result);
            }
            
            public System.IAsyncResult BeginGetMenu(Paradise5.ServiceReference1.GetMenuRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMenu", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.GetMenuResponse EndGetMenu(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.GetMenuResponse _result = ((Paradise5.ServiceReference1.GetMenuResponse)(base.EndInvoke("GetMenu", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginViewMN(Paradise5.ServiceReference1.ViewMNRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ViewMN", _args, callback, asyncState);
                return _result;
            }
            
            public Paradise5.ServiceReference1.ViewMNResponse EndViewMN(System.IAsyncResult result) {
                object[] _args = new object[0];
                Paradise5.ServiceReference1.ViewMNResponse _result = ((Paradise5.ServiceReference1.ViewMNResponse)(base.EndInvoke("ViewMN", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetID(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetID", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetID(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetID", _args, result)));
                return _result;
            }
        }
    }
}
