//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Paradise5.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblSC_Login", Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class tblSC_Login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int LoginIDField;
        
        private string LoginNameField;
        
        private string PassWordField;
        
        private string EmployeeIDField;
        
        private System.Nullable<int> DepartmentIDField;
        
        private System.Nullable<byte> AdminRightField;
        
        private System.Nullable<System.DateTime> LastChangedDateField;
        
        private System.Nullable<int> DivisionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<byte> AdminRight {
            get {
                return this.AdminRightField;
            }
            set {
                if ((this.AdminRightField.Equals(value) != true)) {
                    this.AdminRightField = value;
                    this.RaisePropertyChanged("AdminRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> LastChangedDate {
            get {
                return this.LastChangedDateField;
            }
            set {
                if ((this.LastChangedDateField.Equals(value) != true)) {
                    this.LastChangedDateField = value;
                    this.RaisePropertyChanged("LastChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> DivisionID {
            get {
                return this.DivisionIDField;
            }
            set {
                if ((this.DivisionIDField.Equals(value) != true)) {
                    this.DivisionIDField = value;
                    this.RaisePropertyChanged("DivisionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewMenu", Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class ViewMenu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MenuIDField;
        
        private string NameField;
        
        private string ClassNameField;
        
        private System.Nullable<int> PriorityField;
        
        private string ParentMenuIDField;
        
        private string AssemblyNameField;
        
        private System.Nullable<bool> IsModalField;
        
        private System.Nullable<bool> IsCollapsedField;
        
        private string ShortcutKeysField;
        
        private string LanguageField;
        
        private System.Nullable<bool> IsVisibleField;
        
        private int AccessField;
        
        private System.Nullable<bool> SupperAdminField;
        
        private int LoginIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIDField, value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ParentMenuID {
            get {
                return this.ParentMenuIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentMenuIDField, value) != true)) {
                    this.ParentMenuIDField = value;
                    this.RaisePropertyChanged("ParentMenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string AssemblyName {
            get {
                return this.AssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssemblyNameField, value) != true)) {
                    this.AssemblyNameField = value;
                    this.RaisePropertyChanged("AssemblyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<bool> IsModal {
            get {
                return this.IsModalField;
            }
            set {
                if ((this.IsModalField.Equals(value) != true)) {
                    this.IsModalField = value;
                    this.RaisePropertyChanged("IsModal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<bool> IsCollapsed {
            get {
                return this.IsCollapsedField;
            }
            set {
                if ((this.IsCollapsedField.Equals(value) != true)) {
                    this.IsCollapsedField = value;
                    this.RaisePropertyChanged("IsCollapsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ShortcutKeys {
            get {
                return this.ShortcutKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortcutKeysField, value) != true)) {
                    this.ShortcutKeysField = value;
                    this.RaisePropertyChanged("ShortcutKeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<bool> IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int Access {
            get {
                return this.AccessField;
            }
            set {
                if ((this.AccessField.Equals(value) != true)) {
                    this.AccessField = value;
                    this.RaisePropertyChanged("Access");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> SupperAdmin {
            get {
                return this.SupperAdminField;
            }
            set {
                if ((this.SupperAdminField.Equals(value) != true)) {
                    this.SupperAdminField = value;
                    this.RaisePropertyChanged("SupperAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_EmployeeIDListResult", Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class sp_EmployeeIDListResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmployeeIDField;
        
        private string LastNameField;
        
        private string FirstNameField;
        
        private System.Nullable<short> EmployeeStatusIDField;
        
        private string LastNameENField;
        
        private string FirstNameENField;
        
        private string TitleField;
        
        private string EmailField;
        
        private string FullNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<short> EmployeeStatusID {
            get {
                return this.EmployeeStatusIDField;
            }
            set {
                if ((this.EmployeeStatusIDField.Equals(value) != true)) {
                    this.EmployeeStatusIDField = value;
                    this.RaisePropertyChanged("EmployeeStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LastNameEN {
            get {
                return this.LastNameENField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameENField, value) != true)) {
                    this.LastNameENField = value;
                    this.RaisePropertyChanged("LastNameEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string FirstNameEN {
            get {
                return this.FirstNameENField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameENField, value) != true)) {
                    this.FirstNameENField = value;
                    this.RaisePropertyChanged("FirstNameEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblDepartment", Namespace="http://schemas.datacontract.org/2004/07/Paradise5.Web")]
    public partial class tblDepartment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int DepartmentIDField;
        
        private int DivisionIDField;
        
        private string DepartmentCodeField;
        
        private string DepartmentNameField;
        
        private System.Nullable<int> ForeignerField;
        
        private string JapaneseNameField;
        
        private string VietnameseNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID {
            get {
                return this.DivisionIDField;
            }
            set {
                if ((this.DivisionIDField.Equals(value) != true)) {
                    this.DivisionIDField = value;
                    this.RaisePropertyChanged("DivisionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DepartmentCode {
            get {
                return this.DepartmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCodeField, value) != true)) {
                    this.DepartmentCodeField = value;
                    this.RaisePropertyChanged("DepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> Foreigner {
            get {
                return this.ForeignerField;
            }
            set {
                if ((this.ForeignerField.Equals(value) != true)) {
                    this.ForeignerField = value;
                    this.RaisePropertyChanged("Foreigner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string JapaneseName {
            get {
                return this.JapaneseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JapaneseNameField, value) != true)) {
                    this.JapaneseNameField = value;
                    this.RaisePropertyChanged("JapaneseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string VietnameseName {
            get {
                return this.VietnameseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VietnameseNameField, value) != true)) {
                    this.VietnameseNameField = value;
                    this.RaisePropertyChanged("VietnameseName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.IAsyncResult BeginLogin(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Checklogin", ReplyAction="http://tempuri.org/IService1/CheckloginResponse")]
        System.IAsyncResult BeginChecklogin(string Name, string Pass, System.AsyncCallback callback, object asyncState);
        
        int EndChecklogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetSession", ReplyAction="http://tempuri.org/IService1/SetSessionResponse")]
        System.IAsyncResult BeginSetSession(string UserName, System.AsyncCallback callback, object asyncState);
        
        void EndSetSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSession", ReplyAction="http://tempuri.org/IService1/GetSessionResponse")]
        System.IAsyncResult BeginGetSession(System.AsyncCallback callback, object asyncState);
        
        string EndGetSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RemoveSession", ReplyAction="http://tempuri.org/IService1/RemoveSessionResponse")]
        System.IAsyncResult BeginRemoveSession(System.AsyncCallback callback, object asyncState);
        
        void EndRemoveSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ViewMN", ReplyAction="http://tempuri.org/IService1/ViewMNResponse")]
        System.IAsyncResult BeginViewMN(string Langgue, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> EndViewMN(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetID", ReplyAction="http://tempuri.org/IService1/GetIDResponse")]
        System.IAsyncResult BeginGetID(System.AsyncCallback callback, object asyncState);
        
        int EndGetID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/FindNV", ReplyAction="http://tempuri.org/IService1/FindNVResponse")]
        System.IAsyncResult BeginFindNV(int id, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> EndFindNV(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/danhsachtheocagiolam", ReplyAction="http://tempuri.org/IService1/danhsachtheocagiolamResponse")]
        System.IAsyncResult Begindanhsachtheocagiolam(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> Enddanhsachtheocagiolam(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Paradise5.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewMNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ViewMNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindNVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindNVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class danhsachtheocagiolamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public danhsachtheocagiolamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Paradise5.ServiceReference1.IService1>, Paradise5.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckloginDelegate;
        
        private EndOperationDelegate onEndCheckloginDelegate;
        
        private System.Threading.SendOrPostCallback onCheckloginCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetSessionDelegate;
        
        private EndOperationDelegate onEndSetSessionDelegate;
        
        private System.Threading.SendOrPostCallback onSetSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSessionDelegate;
        
        private EndOperationDelegate onEndGetSessionDelegate;
        
        private System.Threading.SendOrPostCallback onGetSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveSessionDelegate;
        
        private EndOperationDelegate onEndRemoveSessionDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginViewMNDelegate;
        
        private EndOperationDelegate onEndViewMNDelegate;
        
        private System.Threading.SendOrPostCallback onViewMNCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetIDDelegate;
        
        private EndOperationDelegate onEndGetIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindNVDelegate;
        
        private EndOperationDelegate onEndFindNVDelegate;
        
        private System.Threading.SendOrPostCallback onFindNVCompletedDelegate;
        
        private BeginOperationDelegate onBegindanhsachtheocagiolamDelegate;
        
        private EndOperationDelegate onEnddanhsachtheocagiolamDelegate;
        
        private System.Threading.SendOrPostCallback ondanhsachtheocagiolamCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<CheckloginCompletedEventArgs> CheckloginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetSessionCompleted;
        
        public event System.EventHandler<GetSessionCompletedEventArgs> GetSessionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RemoveSessionCompleted;
        
        public event System.EventHandler<ViewMNCompletedEventArgs> ViewMNCompleted;
        
        public event System.EventHandler<GetIDCompletedEventArgs> GetIDCompleted;
        
        public event System.EventHandler<FindNVCompletedEventArgs> FindNVCompleted;
        
        public event System.EventHandler<danhsachtheocagiolamCompletedEventArgs> danhsachtheocagiolamCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginLogin(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> Paradise5.ServiceReference1.IService1.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginLogin(callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync() {
            this.LoginAsync(null);
        }
        
        public void LoginAsync(object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, null, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginChecklogin(string Name, string Pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChecklogin(Name, Pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Paradise5.ServiceReference1.IService1.EndChecklogin(System.IAsyncResult result) {
            return base.Channel.EndChecklogin(result);
        }
        
        private System.IAsyncResult OnBeginChecklogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Name = ((string)(inValues[0]));
            string Pass = ((string)(inValues[1]));
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginChecklogin(Name, Pass, callback, asyncState);
        }
        
        private object[] OnEndChecklogin(System.IAsyncResult result) {
            int retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndChecklogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckloginCompleted(object state) {
            if ((this.CheckloginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckloginCompleted(this, new CheckloginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckloginAsync(string Name, string Pass) {
            this.CheckloginAsync(Name, Pass, null);
        }
        
        public void CheckloginAsync(string Name, string Pass, object userState) {
            if ((this.onBeginCheckloginDelegate == null)) {
                this.onBeginCheckloginDelegate = new BeginOperationDelegate(this.OnBeginChecklogin);
            }
            if ((this.onEndCheckloginDelegate == null)) {
                this.onEndCheckloginDelegate = new EndOperationDelegate(this.OnEndChecklogin);
            }
            if ((this.onCheckloginCompletedDelegate == null)) {
                this.onCheckloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckloginCompleted);
            }
            base.InvokeAsync(this.onBeginCheckloginDelegate, new object[] {
                        Name,
                        Pass}, this.onEndCheckloginDelegate, this.onCheckloginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginSetSession(string UserName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetSession(UserName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Paradise5.ServiceReference1.IService1.EndSetSession(System.IAsyncResult result) {
            base.Channel.EndSetSession(result);
        }
        
        private System.IAsyncResult OnBeginSetSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string UserName = ((string)(inValues[0]));
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginSetSession(UserName, callback, asyncState);
        }
        
        private object[] OnEndSetSession(System.IAsyncResult result) {
            ((Paradise5.ServiceReference1.IService1)(this)).EndSetSession(result);
            return null;
        }
        
        private void OnSetSessionCompleted(object state) {
            if ((this.SetSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetSessionAsync(string UserName) {
            this.SetSessionAsync(UserName, null);
        }
        
        public void SetSessionAsync(string UserName, object userState) {
            if ((this.onBeginSetSessionDelegate == null)) {
                this.onBeginSetSessionDelegate = new BeginOperationDelegate(this.OnBeginSetSession);
            }
            if ((this.onEndSetSessionDelegate == null)) {
                this.onEndSetSessionDelegate = new EndOperationDelegate(this.OnEndSetSession);
            }
            if ((this.onSetSessionCompletedDelegate == null)) {
                this.onSetSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetSessionCompleted);
            }
            base.InvokeAsync(this.onBeginSetSessionDelegate, new object[] {
                        UserName}, this.onEndSetSessionDelegate, this.onSetSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginGetSession(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSession(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Paradise5.ServiceReference1.IService1.EndGetSession(System.IAsyncResult result) {
            return base.Channel.EndGetSession(result);
        }
        
        private System.IAsyncResult OnBeginGetSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginGetSession(callback, asyncState);
        }
        
        private object[] OnEndGetSession(System.IAsyncResult result) {
            string retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndGetSession(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSessionCompleted(object state) {
            if ((this.GetSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSessionCompleted(this, new GetSessionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSessionAsync() {
            this.GetSessionAsync(null);
        }
        
        public void GetSessionAsync(object userState) {
            if ((this.onBeginGetSessionDelegate == null)) {
                this.onBeginGetSessionDelegate = new BeginOperationDelegate(this.OnBeginGetSession);
            }
            if ((this.onEndGetSessionDelegate == null)) {
                this.onEndGetSessionDelegate = new EndOperationDelegate(this.OnEndGetSession);
            }
            if ((this.onGetSessionCompletedDelegate == null)) {
                this.onGetSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSessionCompleted);
            }
            base.InvokeAsync(this.onBeginGetSessionDelegate, null, this.onEndGetSessionDelegate, this.onGetSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginRemoveSession(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveSession(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Paradise5.ServiceReference1.IService1.EndRemoveSession(System.IAsyncResult result) {
            base.Channel.EndRemoveSession(result);
        }
        
        private System.IAsyncResult OnBeginRemoveSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginRemoveSession(callback, asyncState);
        }
        
        private object[] OnEndRemoveSession(System.IAsyncResult result) {
            ((Paradise5.ServiceReference1.IService1)(this)).EndRemoveSession(result);
            return null;
        }
        
        private void OnRemoveSessionCompleted(object state) {
            if ((this.RemoveSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveSessionAsync() {
            this.RemoveSessionAsync(null);
        }
        
        public void RemoveSessionAsync(object userState) {
            if ((this.onBeginRemoveSessionDelegate == null)) {
                this.onBeginRemoveSessionDelegate = new BeginOperationDelegate(this.OnBeginRemoveSession);
            }
            if ((this.onEndRemoveSessionDelegate == null)) {
                this.onEndRemoveSessionDelegate = new EndOperationDelegate(this.OnEndRemoveSession);
            }
            if ((this.onRemoveSessionCompletedDelegate == null)) {
                this.onRemoveSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveSessionCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveSessionDelegate, null, this.onEndRemoveSessionDelegate, this.onRemoveSessionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginViewMN(string Langgue, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginViewMN(Langgue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> Paradise5.ServiceReference1.IService1.EndViewMN(System.IAsyncResult result) {
            return base.Channel.EndViewMN(result);
        }
        
        private System.IAsyncResult OnBeginViewMN(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Langgue = ((string)(inValues[0]));
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginViewMN(Langgue, callback, asyncState);
        }
        
        private object[] OnEndViewMN(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndViewMN(result);
            return new object[] {
                    retVal};
        }
        
        private void OnViewMNCompleted(object state) {
            if ((this.ViewMNCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ViewMNCompleted(this, new ViewMNCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ViewMNAsync(string Langgue) {
            this.ViewMNAsync(Langgue, null);
        }
        
        public void ViewMNAsync(string Langgue, object userState) {
            if ((this.onBeginViewMNDelegate == null)) {
                this.onBeginViewMNDelegate = new BeginOperationDelegate(this.OnBeginViewMN);
            }
            if ((this.onEndViewMNDelegate == null)) {
                this.onEndViewMNDelegate = new EndOperationDelegate(this.OnEndViewMN);
            }
            if ((this.onViewMNCompletedDelegate == null)) {
                this.onViewMNCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnViewMNCompleted);
            }
            base.InvokeAsync(this.onBeginViewMNDelegate, new object[] {
                        Langgue}, this.onEndViewMNDelegate, this.onViewMNCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginGetID(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetID(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Paradise5.ServiceReference1.IService1.EndGetID(System.IAsyncResult result) {
            return base.Channel.EndGetID(result);
        }
        
        private System.IAsyncResult OnBeginGetID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginGetID(callback, asyncState);
        }
        
        private object[] OnEndGetID(System.IAsyncResult result) {
            int retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndGetID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetIDCompleted(object state) {
            if ((this.GetIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetIDCompleted(this, new GetIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetIDAsync() {
            this.GetIDAsync(null);
        }
        
        public void GetIDAsync(object userState) {
            if ((this.onBeginGetIDDelegate == null)) {
                this.onBeginGetIDDelegate = new BeginOperationDelegate(this.OnBeginGetID);
            }
            if ((this.onEndGetIDDelegate == null)) {
                this.onEndGetIDDelegate = new EndOperationDelegate(this.OnEndGetID);
            }
            if ((this.onGetIDCompletedDelegate == null)) {
                this.onGetIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetIDDelegate, null, this.onEndGetIDDelegate, this.onGetIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.BeginFindNV(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindNV(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> Paradise5.ServiceReference1.IService1.EndFindNV(System.IAsyncResult result) {
            return base.Channel.EndFindNV(result);
        }
        
        private System.IAsyncResult OnBeginFindNV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((Paradise5.ServiceReference1.IService1)(this)).BeginFindNV(id, callback, asyncState);
        }
        
        private object[] OnEndFindNV(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> retVal = ((Paradise5.ServiceReference1.IService1)(this)).EndFindNV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindNVCompleted(object state) {
            if ((this.FindNVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindNVCompleted(this, new FindNVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindNVAsync(int id) {
            this.FindNVAsync(id, null);
        }
        
        public void FindNVAsync(int id, object userState) {
            if ((this.onBeginFindNVDelegate == null)) {
                this.onBeginFindNVDelegate = new BeginOperationDelegate(this.OnBeginFindNV);
            }
            if ((this.onEndFindNVDelegate == null)) {
                this.onEndFindNVDelegate = new EndOperationDelegate(this.OnEndFindNV);
            }
            if ((this.onFindNVCompletedDelegate == null)) {
                this.onFindNVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindNVCompleted);
            }
            base.InvokeAsync(this.onBeginFindNVDelegate, new object[] {
                        id}, this.onEndFindNVDelegate, this.onFindNVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Paradise5.ServiceReference1.IService1.Begindanhsachtheocagiolam(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindanhsachtheocagiolam(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> Paradise5.ServiceReference1.IService1.Enddanhsachtheocagiolam(System.IAsyncResult result) {
            return base.Channel.Enddanhsachtheocagiolam(result);
        }
        
        private System.IAsyncResult OnBegindanhsachtheocagiolam(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Paradise5.ServiceReference1.IService1)(this)).Begindanhsachtheocagiolam(callback, asyncState);
        }
        
        private object[] OnEnddanhsachtheocagiolam(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> retVal = ((Paradise5.ServiceReference1.IService1)(this)).Enddanhsachtheocagiolam(result);
            return new object[] {
                    retVal};
        }
        
        private void OndanhsachtheocagiolamCompleted(object state) {
            if ((this.danhsachtheocagiolamCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.danhsachtheocagiolamCompleted(this, new danhsachtheocagiolamCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void danhsachtheocagiolamAsync() {
            this.danhsachtheocagiolamAsync(null);
        }
        
        public void danhsachtheocagiolamAsync(object userState) {
            if ((this.onBegindanhsachtheocagiolamDelegate == null)) {
                this.onBegindanhsachtheocagiolamDelegate = new BeginOperationDelegate(this.OnBegindanhsachtheocagiolam);
            }
            if ((this.onEnddanhsachtheocagiolamDelegate == null)) {
                this.onEnddanhsachtheocagiolamDelegate = new EndOperationDelegate(this.OnEnddanhsachtheocagiolam);
            }
            if ((this.ondanhsachtheocagiolamCompletedDelegate == null)) {
                this.ondanhsachtheocagiolamCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndanhsachtheocagiolamCompleted);
            }
            base.InvokeAsync(this.onBegindanhsachtheocagiolamDelegate, null, this.onEnddanhsachtheocagiolamDelegate, this.ondanhsachtheocagiolamCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Paradise5.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Paradise5.ServiceReference1.IService1>, Paradise5.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Paradise5.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login> _result = ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblSC_Login>)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChecklogin(string Name, string Pass, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = Name;
                _args[1] = Pass;
                System.IAsyncResult _result = base.BeginInvoke("Checklogin", _args, callback, asyncState);
                return _result;
            }
            
            public int EndChecklogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Checklogin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetSession(string UserName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = UserName;
                System.IAsyncResult _result = base.BeginInvoke("SetSession", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSetSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SetSession", _args, result);
            }
            
            public System.IAsyncResult BeginGetSession(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSession", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetSession", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemoveSession(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("RemoveSession", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRemoveSession(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RemoveSession", _args, result);
            }
            
            public System.IAsyncResult BeginViewMN(string Langgue, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Langgue;
                System.IAsyncResult _result = base.BeginInvoke("ViewMN", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> EndViewMN(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu> _result = ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.ViewMenu>)(base.EndInvoke("ViewMN", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetID(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetID", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetID(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFindNV(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("FindNV", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> EndFindNV(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult> _result = ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.sp_EmployeeIDListResult>)(base.EndInvoke("FindNV", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Begindanhsachtheocagiolam(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("danhsachtheocagiolam", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> Enddanhsachtheocagiolam(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment> _result = ((System.Collections.ObjectModel.ObservableCollection<Paradise5.ServiceReference1.tblDepartment>)(base.EndInvoke("danhsachtheocagiolam", _args, result)));
                return _result;
            }
        }
    }
}
